language: php
php: 7.0.19
dist: trusty
sudo: true

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache/files

services:
  - mysql

before_install:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE mnemonic;' 

install:
  - cp .env.ci .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - travis_retry php artisan db:seed
  - npm install
  - npm run dev

script:
  - vendor/bin/phpunit
