language: php
php: 
   - 7.0.19
dist: trusty
sudo: false

services:
   - mysql

before_install:
   - mysql -e 'CREATE DATABASE mnemonic;' 

install:
   - cp .env.ci .env
   - travis_retry composer install --dev --no-interaction --prefer-dist --no-suggest
   - php artisan key:generate
   - php artisan migrate
   - php artisan db:seed

script:
   - vendor/bin/phpunit
