language: php
php: 7.0
dist: trusty
sudo: false

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache/files

services:
  - mysql

install:
  - cp tests/.env.tests .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - yarn install
  - yarn run dev
  - php artisan key:generate
  - mysql -e 'CREATE DATABASE mnemonic;' 
  - php artisan migrate
  - php artisan db:seed

script:
  - vendor/bin/phpunit
